fail_fast: false
exclude: ^.*\b(migrations)\b.*$
repos:
  - repo: 'https://github.com/asottile/pyupgrade'
    rev: v3.15.2
    hooks:
      - id: pyupgrade
        args:
          - '--py38-plus'
  - repo: 'https://github.com/myint/autoflake'
    rev: v2.3.1
    hooks:
      - id: autoflake
        args:
          - '--in-place'
          - '--remove-all-unused-imports'
          - '--ignore-init-module-imports'
          - '--remove-unused-variables'
  - repo: 'https://github.com/myint/docformatter'
    rev: v1.7.5
    hooks:
      - id: docformatter
        args:
          - '--in-place'
          - '--blank'
  - repo: 'https://github.com/pycqa/flake8'
    rev: 7.0.0
    hooks:
      - id: flake8
        args:
          - '--config=.flake8'
          - '--max-line-length=120'
          - '--ignore=E704, E701, E203, W503, A003, DUO102'
        exclude: .git|__pycache__
        additional_dependencies:
          - flake8-builtins>=2.5.0
          - flake8-debugger>=4.1.2
          - flake8-comprehensions>=3.14.0
          - flake8-eradicate>=1.4.0
          - dlint>=0.11.0
  - repo: 'https://github.com/astral-sh/ruff-pre-commit'
    rev: v0.4.3
    hooks:
      - id: ruff
        args:
        - '--line-length=120'
      - id: ruff-format
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace